modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="ourmagic"
version="1.0.0"
displayName="OurMagic"
description='''A Forge-native wand-focused recreation of Magic's core wand play loop.'''

[[dependencies.ourmagic]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.ourmagic]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
